// alt_mge_xcvr_reset_ctrl_txpll.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module alt_mge_xcvr_reset_ctrl_txpll (
		input  wire       clock,         //         clock.clk
		input  wire       reset,         //         reset.reset
		output wire [0:0] pll_powerdown  // pll_powerdown.pll_powerdown
	);

	altera_xcvr_reset_control #(
		.CHANNELS              (1),
		.PLLS                  (1),
		.SYS_CLK_IN_MHZ        (125),
		.SYNCHRONIZE_RESET     (1),
		.REDUCED_SIM_TIME      (1),
		.TX_PLL_ENABLE         (1),
		.T_PLL_POWERDOWN       (70000),
		.SYNCHRONIZE_PLL_RESET (1),
		.TX_ENABLE             (0),
		.TX_PER_CHANNEL        (0),
		.T_TX_ANALOGRESET      (0),
		.T_TX_DIGITALRESET     (20),
		.T_PLL_LOCK_HYST       (0),
		.EN_PLL_CAL_BUSY       (0),
		.RX_ENABLE             (0),
		.RX_PER_CHANNEL        (0),
		.T_RX_ANALOGRESET      (40),
		.T_RX_DIGITALRESET     (4000)
	) xcvr_reset_control_0 (
		.clock              (clock),         //   input,  width = 1,         clock.clk
		.reset              (reset),         //   input,  width = 1,         reset.reset
		.pll_powerdown      (pll_powerdown), //  output,  width = 1, pll_powerdown.pll_powerdown
		.tx_analogreset     (),              // (terminated),                           
		.tx_digitalreset    (),              // (terminated),                           
		.tx_ready           (),              // (terminated),                           
		.pll_locked         (1'b0),          // (terminated),                           
		.pll_select         (1'b0),          // (terminated),                           
		.tx_cal_busy        (1'b0),          // (terminated),                           
		.pll_cal_busy       (1'b0),          // (terminated),                           
		.tx_manual          (1'b0),          // (terminated),                           
		.rx_analogreset     (),              // (terminated),                           
		.rx_digitalreset    (),              // (terminated),                           
		.rx_ready           (),              // (terminated),                           
		.rx_is_lockedtodata (1'b0),          // (terminated),                           
		.rx_cal_busy        (1'b0),          // (terminated),                           
		.rx_manual          (1'b0),          // (terminated),                           
		.tx_digitalreset_or (1'b0),          // (terminated),                           
		.rx_digitalreset_or (1'b0)           // (terminated),                           
	);

endmodule
